<div class="container" style="margin-top:10px;">
    <div id="map">
        Sit back and relax! Map is initializing...
    </div>
</div>

<?php
$this->inlineScript()->captureStart();
echo <<<JS
    window.GOOGLE_API_KEY = '${google_api_key}';
JS;
echo <<<JS
    window.onload = function() {
        $("document").ready(function() { mapIndexInit(); })
    }
JS;
$this->inlineScript()->captureEnd();
?>